export enum UbiquitousLanguagePattern {
  BOUNDED_CONTEXT = 'BOUNDED_CONTEXT',
  AGGREGATE = 'AGGREGATE',
  DOMAIN_ENTITY = 'DOMAIN_ENTITY',
  VALUE_OBJECT = 'VALUE_OBJECT',
  DOMAIN_COMMAND = 'DOMAIN_COMMAND',
  DOMAIN_EVENT = 'DOMAIN_EVENT',
  FACTORY = 'FACTORY',
  REPOSITORY = 'DOMAIN_REPOSITORY',
  DOMAIN_SERVICE = 'DOMAIN_SERVICE',
}
