name: Publish a new release

on:
  push:
    branches:
    - feat/JsonAdapter

jobs:
  release:
    name: Semantic-Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.16
        cache: npm

    - name: Install dependencies
      run: npm install

    - name: Semantic release
      uses: cycjimmy/semantic-release-action@v3
      with:
        extra_plugin: semantic-release-gitmoji
        extends: semantic-release-config-gitmoji
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
